version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET=${SECRET}
      - MONGODB_URI=mongodb+srv://${DB_USER}:${DB_PASS}@cluster0.z1he7zj.mongodb.net/?retryWrites=true&w=majority
      - JWT_SECRET=${SECRET}
    depends_on:
      - mongodb
